### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by simplew2011** [cxzhou95/XLSR#11]
![image](https://github.com/cxzhou95/XLSR/assets/66729924/c08b6eed-7989-4df3-8019-2f61105e5201)

**Comment by simplew2011** [comment]
![image](https://github.com/cxzhou95/XLSR/assets/66729924/088b97a3-aef2-4fd9-9d1a-8cb07e9f3757)

**Comment by simplew2011** [comment]
> ![image](https://user-images.githubusercontent.com/66729924/259279832-088b97a3-aef2-4fd9-9d1a-8cb07e9f3757.png)

modify torch 1.8 to 1.12 is ok

**Comment by arianaa30** [comment]
Hi, where you able to find a way to load the quantized models? 'best.pt' loads fine, but not the quantized models.

**Comment by arianaa30** [comment]
While loading the regular `best.pt` model works, but loading the quantized models (like `QAT_quantized_model.pt`) throws an error. What is the problem?

`python test.py --model exp/OneCyclicLR/QAT_quantized_model.pt --device cpu`

Error: 
```
C:\Users\AppData\Local\anaconda3\Lib\site-packages\torch\serialization.py:995: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last):
  File "C:\Users\Downloads\XLSR\test.py", line 109, in <module>
    model.load_state_dict(torch.load(opt.model, map_location=device))
  File "C:\Users\AppData\Local\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 2103, in load_state_dict
    raise TypeError(f"Expected state_dict to be dict-like, got {type(state_dict)}.")
TypeError: Expected state_dict to be dict-like, got <class 'torch.jit._script.RecursiveScriptModule'>.
```
